steps:
- name: 'gcr.io/spiredigital-222419/spiredigital-wp-docker'
  args: ['build', '-t', 'gcr.io/spiredigital-222419/bitnami-docker-wordpress:1.0.$SHORT_SHA', './4/debian-9']
  timeout: 180s
- name: 'gcr.io/spiredigital-222419/spiredigital-docker'
  args: ['push', 'gcr.io/spiredigital-222419/bitnami-docker-wordpress:1.0.$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - devblog-spiredigital-com-wordpress
  - web=gcr.io/spiredigital-222419/bitnami-docker-wordpress:1.0.$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spiredigital-gke'
